version: '3.8'

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: aries_zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: bitnami/kafka:latest
    container_name: aries_kafka
    ports:
    - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSET_TOPIC_REPLICATION_FACTOR: 1

  postgres:
    image: postgres:latest
    container_name: aries_postgres
    environment:
      POSTGRES_USER: aries_user
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: aries_db
    ports:
      - "5432:5432"