version: '3.8'

services:
  kafka:
    image: bitnami/kafka:latest
    container_name: aries_kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_NODE_ID: "1"
      KAFKA_CFG_PROCESS_ROLES: "broker,controller"
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_KRAFT_CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
    volumes:
      - type: volume
        source: kafka_data
        target: /bitnami/kafka
      
  postgres:
    image: postgres:latest
    container_name: aries_postgres
    environment:
      POSTGRES_USER: "aries_user"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "aries_db"
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data

volumes:
  kafka_data:
    driver: local
  postgres_data:
    driver: local